version: '3'

services:
  dora:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./src/backend:/root/dora/backend
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - dora-mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

  osm:
    build:
      context: ./openstreetmap-tile-server
      dockerfile: dockerfile
    image: osm/rebuilt
    command: run
    restart: always
    volumes:
      - osm-data:/data/database
      - osm-tiles:/data/tiles
    ports:
      - 8000:80

  hostap:
    build:
      context: ./rpi-ap
      dockerfile: dockerfile
    environment:
      MODE: wpa2
      SSID: dora
      WPA2_PASS: password
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    network_mode: "host"
    privileged: true
    restart: always

volumes:
  dora-mongo:
  osm-data:
    external: true
  osm-tiles:
    external: true

